/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-iCal.h
 #	source generated by 4D Plugin Wizard
 #	Project : iCal
 #	author : miyako
 #	2020/03/17
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_ICAL_H
#define PLUGIN_ICAL_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"

#include <mutex>

#import <Cocoa/Cocoa.h>
#import <EventKit/EventKit.h>
#import <Security/Security.h>
#import <CalendarStore/CalendarStore.h>

#pragma mark -

void iCal_Request_permisson(PA_PluginParameters params);

typedef enum {
    
    request_permission_unknown = 0,
    request_permission_authorized = 1,
    request_permission_not_determined = 2,
    request_permission_denied = 3,
    request_permission_restricted = 4
    
}request_permission_t;

// --- Calendar Store
void iCal_QUERY_EVENT(PA_PluginParameters params);
void iCal_GET_CALENDAR_LIST(PA_PluginParameters params);

// --- Calendar
void iCal_Create_calendar(PA_PluginParameters params);
void iCal_Set_calendar_property(PA_PluginParameters params);
void iCal_Get_calendar_property(PA_PluginParameters params);
void iCal_Remove_calendar(PA_PluginParameters params);

#endif /* PLUGIN_ICAL_H */
